### ISSUE TITLE
Wrong value for beta used?

### ISSUE THREAD

**Issue by tomasstolker** [wbalmer/backtrack#14]
Should this presumably be `beta = self.beta` instead of `beta = self.alpha`?

https://github.com/wbalmer/backtrack/blob/930c57124dea87df3f73430150265ce07949746a/backtrack/backtrack.py#L314

**Comment by gotten** [comment]
Does look like it should indeed be beta= self.beta. The values in the comments still refer to the Gaia DR2 priors, so I should clean that up. The method implemented here is the generalized gamma distribution from Gaia DR3.

**Comment by wbalmer** [comment]
Corrected in PR #13
