### ISSUE TITLE
Posterior quantiles

### ISSUE THREAD

**Issue by tomasstolker** [wbalmer/backtrack#15]
Should we change this to 16th and 84th percentiles? Which are more common to quote as uncertainties?

https://github.com/wbalmer/backtrack/blob/930c57124dea87df3f73430150265ce07949746a/backtrack/backtrack.py#L453

**Comment by gotten** [comment]
I'm not too familiar with dynesty. After looking at the code it seems it calculates quantiles for each of the parameters and stores it in the pkl results files. It also uses them to draw parameters for the trackplots (labeled 1 sigma). So 0.16, 0.84 sound like the correct quantiles as you suggest. However taking the lower and upper 1 sigma value of each of the parameters combined will not be the same as plotting the 1 sigma contour for where we can find our star (our parameters are not independent). Which is a different problem highlighted by https://github.com/wbalmer/backtrack/pull/13 . So: 0.16, 0.84 is better as it gives correct values in the pkl files, but we probably need to rewrite part of the code in the plotting routine to show actual 1 sigma probabilities in the trackplots.

**Comment by wbalmer** [comment]
for some reason while i wrote that line of code i thought that 0.5+/-0.18 = [0.32,0.68] was the 1 sigma interval, but that must have been late night coding (probably while up observing). this should be corrected in commit [de0e8f6](https://github.com/wbalmer/backtrack/commit/de0e8f690666fa95db855aabc9513cb8fb7353bc) and folded into PR #18
